name: Bug confirmed label

on:
  project_card:
    types:
      - moved

jobs:
  remove_labels:
    if: github.event.project_card.column_id == '17295560'

    runs-on: ubuntu-latest

    steps:
      - name: add labels
        uses: andymckay/labeler@v1
        with:
          add-labels: "confirmed"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
