name: "Lint GitHub Actions"

on:
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
